"use client";

import React, { useRef } from 'react';
import { motion, useInView, Variants } from 'framer-motion';
import { Card } from '../ui/Card';
import { 
  UserPlus, 
  CalendarDays, 
  Percent, 
  ArrowUpCircle, 
  Users 
} from 'lucide-react';

const earningsMetrics = [
  {
    title: "Registration Bonus",
    value: "₦7,000 per expert",
    desc: "Upfront payment for every verified expert you recruit into the ecosystem.",
    icon: <UserPlus className="text-primary" />,
  },
  {
    title: "Model 2 Commission",
    value: "1% of every job",
    desc: "Lifetime variable commission from every service fee generated by your recruited experts.",
    icon: <Percent className="text-white" />,
    isFeatured: true,
  },
  {
    title: "Model 1 Commission",
    value: "₦1,000 per month",
    desc: "Fixed monthly recurring commission for every active expert under your management.",
    icon: <CalendarDays className="text-primary" />,
  },
  {
    title: "Tier Bonus",
    value: "Up to +15%",
    desc: "Performance-based multiplier that boosts your total monthly earnings as you rank up.",
    icon: <ArrowUpCircle className="text-primary" />,
  },
  {
    title: "Sub-TAS Override",
    value: "0.1% - 0.2%",
    desc: "Earn ongoing overrides from the recruitment efforts of the agents you mentor.",
    icon: <Users className="text-primary" />,
  }
];

/* ── Animation Variants ────────────────────────────────────────── */
const containerVariants: Variants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.1,
      delayChildren: 0.2,
    },
  },
};

const itemVariants: Variants = {
  hidden: { opacity: 0, y: 30, scale: 0.95 },
  visible: { 
    opacity: 1, 
    y: 0, 
    scale: 1,
    transition: { duration: 0.6, ease: [0.22, 1, 0.36, 1] } 
  },
};

export const TASEarningsGrid: React.FC = () => {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: "-100px" });

  const topRow = earningsMetrics.slice(0, 2);    // Registration + Model 2 (featured)
  const bottomRow = earningsMetrics.slice(2);    // Model 1, Tier Bonus, Sub-TAS

  return (
    <section className="py-24 bg-background px-6 overflow-hidden">
      <div className="max-w-7xl mx-auto">

        {/* Header */}
        <motion.div
          initial={{ opacity: 0, x: -20 }}
          animate={isInView ? { opacity: 1, x: 0 } : {}}
          className="mb-16"
        >
          <span className="text-secondary text-[10px] font-black uppercase tracking-[0.3em] mb-4 block">
            Partner Revenue
          </span>
          <h2 className="text-text-main font-display text-4xl md:text-5xl font-bold">
            Earnings Overview
          </h2>
          <p className="text-text-muted mt-4 max-w-xl font-medium">
            Multiple streams of income designed to reward both recruitment and long-term network management.
          </p>
        </motion.div>

        <motion.div
          ref={ref}
          variants={containerVariants}
          initial="hidden"
          animate={isInView ? "visible" : "hidden"}
          className="flex flex-col gap-8"
        >
          {/* Top row — 2 wide cards */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {topRow.map((metric, i) => (
              <motion.div
                key={i}
                variants={itemVariants}
                whileHover={metric.isFeatured ? { scale: 1.05, rotateZ: 1 } : { y: -8 }}
                className="h-full"
              >
                <Card
                  className={`p-10 rounded-[2.5rem] shadow-ambient transition-all duration-500 border border-slate-100! flex flex-col h-full
                    ${metric.isFeatured
                      ? 'bg-primary! text-white border-none! shadow-2xl shadow-primary/20'
                      : 'bg-surface hover:border-primary/20'
                    }`}
                >
                  <motion.div
                    whileHover={{ rotate: -10, scale: 1.1 }}
                    className={`w-14 h-14 rounded-2xl flex items-center justify-center mb-8 shrink-0
                      ${metric.isFeatured ? 'bg-white/10' : 'bg-primary/5'}`}
                  >
                    {metric.icon}
                  </motion.div>

                  <div className="flex-1">
                    <h3 className={`text-[10px] font-black uppercase tracking-[0.2em] mb-3
                      ${metric.isFeatured ? 'text-white/60' : 'text-text-muted'}`}>
                      {metric.title}
                    </h3>
                    <p className={`text-2xl md:text-3xl font-display font-black mb-4 tracking-tight
                      ${metric.isFeatured ? 'text-white' : 'text-text-main'}`}>
                      {metric.value}
                    </p>
                    <p className={`text-sm leading-relaxed font-medium
                      ${metric.isFeatured ? 'text-white/80' : 'text-text-muted'}`}>
                      {metric.desc}
                    </p>
                  </div>

                  {metric.isFeatured && (
                    <div className="mt-8 pt-6 border-t border-white/10">
                      <span className="text-[9px] font-black uppercase tracking-widest text-white/40 italic">
                        ● Highest Passive Potential
                      </span>
                    </div>
                  )}
                </Card>
              </motion.div>
            ))}
          </div>

          {/* Bottom row — 3 narrow cards */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {bottomRow.map((metric, i) => (
              <motion.div
                key={i}
                variants={itemVariants}
                whileHover={{ y: -8 }}
                className="h-full"
              >
                <Card
                  className="p-10 rounded-[2.5rem] shadow-ambient transition-all duration-500 border border-slate-100! bg-surface hover:border-primary/20 flex flex-col h-full"
                >
                  <motion.div
                    whileHover={{ rotate: -10, scale: 1.1 }}
                    className="w-14 h-14 rounded-2xl flex items-center justify-center mb-8 shrink-0 bg-primary/5"
                  >
                    {metric.icon}
                  </motion.div>

                  <div className="flex-1">
                    <h3 className="text-[10px] font-black uppercase tracking-[0.2em] mb-3 text-text-muted">
                      {metric.title}
                    </h3>
                    <p className="text-2xl md:text-3xl font-display font-black mb-4 tracking-tight text-text-main">
                      {metric.value}
                    </p>
                    <p className="text-sm leading-relaxed font-medium text-text-muted">
                      {metric.desc}
                    </p>
                  </div>
                </Card>
              </motion.div>
            ))}
          </div>
        </motion.div>

      </div>
    </section>
  );
};