import React from 'react';
import { Card } from '../ui/Card';
import { UserPlus, Banknote, TrendingUp } from 'lucide-react';

const earningsMetrics = [
  {
    title: "Registration Bonus",
    value: "₦7,000 per expert",
    desc: "Earn instantly for every verified expert who completes their first project through your link.",
    icon: <UserPlus className="text-primary" />,
    color: "bg-blue-50"
  },
  {
    title: "Lifetime Commissions",
    value: "1% - 2% of every job",
    desc: "Receive ongoing commission from every service fee generated by your recruited experts.",
    icon: <Banknote className="text-white" />,
    color: "bg-primary text-white", // Highlighted card as seen in design
    isDark: true
  },
  {
    title: "Tier Bonus",
    value: "Up to +15% Boost",
    desc: "Unlock quarterly performance multipliers as you climb the TAS ranks and build your team.",
    icon: <TrendingUp className="text-primary" />,
    color: "bg-purple-50"
  }
];

export const TASEarningsGrid: React.FC = () => {
  return (
    <section className="py-24 bg-white">
      <div className="max-w-7xl mx-auto px-6">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {earningsMetrics.map((metric, i) => (
            <Card 
              key={i} 
              className={`p-10 border-none rounded-[2.5rem] shadow-sm transition-all hover:shadow-xl ${metric.color}`}
            >
              <div className={`w-14 h-14 rounded-2xl flex items-center justify-center mb-8 ${metric.isDark ? 'bg-white/10' : 'bg-white shadow-sm'}`}>
                {metric.icon}
              </div>
              <h3 className={`text-sm font-bold uppercase tracking-widest mb-2 ${metric.isDark ? 'text-white/60' : 'text-gray-400'}`}>
                {metric.title}
              </h3>
              <p className={`text-2xl font-bold mb-4 ${metric.isDark ? 'text-white' : 'text-primary'}`}>
                {metric.value}
              </p>
              <p className={`text-sm leading-relaxed ${metric.isDark ? 'text-white/70' : 'text-gray-500'}`}>
                {metric.desc}
              </p>
            </Card>
          ))}
        </div>
      </div>
    </section>
  );
};